package server

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"sort"
	"strconv"
	"strings"

	tile57 "github.com/beetlebugorg/tile57/bindings/go"
)

// serveTile57Style returns a complete MapLibre style document generated by the
// native tile57 engine (tile57_style_template + tile57_build_style over the S-52
// colortables baked into libtile57), so the style itself — not just the tiles and
// symbology assets — comes from the engine. Query params (all optional):
//
//	scheme  day|dusk|night            (default day)
//	tiles   chart {z}/{x}/{y} URL     (default <origin>/tiles/tile57/{z}/{x}/{y}.mvt)
//	sprite  sprite base URL           (default <origin>/sprite)
//	glyphs  glyphs URL                (default <origin>/glyphs/{fontstack}/{range}.pbf)
//	bands   CSV of band ranks to show (default all)
//
// The FULL S-52 mariner selection is read from the query too (marinerFromQuery) —
// the client's DEFAULT_MARINER keys (display categories, contours, boundary/point
// style, text groups, dates, viewingGroupsOff, sizeScale, …) — so the engine bakes
// the live display state into the style and the client re-fetches on a toggle.
//
// CORS-open like the tile + asset routes so a static-hosted client can fetch it.
func (s *Server) serveTile57Style(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	if r.Method != http.MethodGet {
		apiErr(w, http.StatusMethodNotAllowed, "GET only")
		return
	}
	q := r.URL.Query()
	// libtile57 is the sole engine, so EVERY registered provider renders from the engine
	// style. ?set is a CSV of PROVIDERS (default: all registered) — one for a single-
	// provider install, several across providers (each a self-contained best-available
	// provider archive; districts live inside one archive, not as separate sources). 404
	// only when nothing is registered.
	sets := s.resolveStyleSets(q.Get("set"))
	if len(sets) == 0 {
		apiErr(w, http.StatusNotFound, "no renderable tile57 set")
		return
	}
	m := marinerFromQuery(q)
	var style []byte
	var err error
	if len(sets) == 1 {
		style, err = s.styleCtxForSet(r, q, sets[0]).build(m)
	} else {
		style, err = s.buildMultiStyle(r, q, sets, m)
	}
	if err != nil {
		apiErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeMaybeGzip(w, r, jsonCT, style) // the engine style is multi-MB — gzip on the wire
}

// buildMultiStyle composes ONE MapLibre style spanning several PROVIDERS: it builds the
// engine style for each provider set (each with its own SCAMIN ladder + top zoom) and
// merges them, namespacing every set's "chart" source + layers so they coexist. The
// sets are ordered coarse→fine, so a finer provider's layers draw over a coarser one
// where they overlap. Within a provider, best-available across cells/districts is
// already resolved inside its single archive (the baker's finestCsclAt), so this cross-
// source merge now only spans the handful of installed providers (noaa/ienc/user),
// which are normally geographically disjoint — the per-district explosion is gone.
func (s *Server) buildMultiStyle(r *http.Request, q url.Values, sets []string, m tile57.Mariner) ([]byte, error) {
	parts := make([]setStyle, 0, len(sets))
	for _, set := range sets {
		b, err := s.styleCtxForSet(r, q, set).build(m)
		if err != nil {
			continue // a set that fails to build is skipped, not fatal
		}
		parts = append(parts, setStyle{set: set, style: b})
	}
	if len(parts) == 0 {
		return nil, fmt.Errorf("no set produced a style")
	}
	return mergeStyles(parts)
}

// setStyle is one pack's single-source engine style, tagged with its set name.
type setStyle struct {
	set   string
	style []byte
}

// mergeStyles merges per-set single-source styles into one multi-source style. Each
// set's "chart" source becomes "chart-<set>" and each layer's id gets a "--<set>"
// suffix (source ref rewritten to match); backgrounds are dropped (the client's
// chrome supplies one) and sprite/glyphs are taken from the first part.
func mergeStyles(parts []setStyle) ([]byte, error) {
	out := map[string]any{"version": 8}
	sources := map[string]any{}
	layers := make([]any, 0, len(parts)*40)
	for i, p := range parts {
		var st map[string]any
		if err := json.Unmarshal(p.style, &st); err != nil {
			return nil, err
		}
		if i == 0 {
			for _, k := range []string{"sprite", "glyphs"} {
				if v, ok := st[k]; ok {
					out[k] = v
				}
			}
		}
		if srcs, ok := st["sources"].(map[string]any); ok {
			for k, v := range srcs {
				sources[chartSrcKey(k, p.set)] = v
			}
		}
		if lyrs, ok := st["layers"].([]any); ok {
			for _, l := range lyrs {
				lm, ok := l.(map[string]any)
				if !ok || lm["type"] == "background" {
					continue
				}
				if src, ok := lm["source"].(string); ok {
					lm["source"] = chartSrcKey(src, p.set)
				}
				if id, ok := lm["id"].(string); ok {
					lm["id"] = id + "--" + p.set
				}
				layers = append(layers, lm)
			}
		}
	}
	out["sources"] = sources
	out["layers"] = layers
	return json.Marshal(out)
}

// chartSrcKey namespaces the engine's single "chart" source per set; any other
// source name (there are none today) passes through.
func chartSrcKey(name, set string) string {
	if name == "chart" {
		return "chart-" + set
	}
	return name
}

// serveTile57StyleDiff returns the minimal MapLibre mutation ops to move the style from
// one mariner selection to another, so the client applies a toggle IN PLACE
// (setFilter/setPaintProperty/setLayoutProperty) with no setStyle — no tile reload, no
// overlay churn, no flicker. This is the host-side stand-in for the engine's future
// tile57_style_diff (../tile57 specs/style-diff.md): it builds both full styles here and
// structurally diffs them (style_diff.go). When the ABI lands, only this body changes;
// the op-array contract to the client is identical.
//
//	POST /api/style-diff   body: {"from":"<mariner query>","to":"<mariner query>"}
//
// `from`/`to` are url-encoded mariner queries — the same string the client builds for
// /api/style.json — so the two styles share this request's set/urls/scamin/lat context
// and differ ONLY in the mariner.
func (s *Server) serveTile57StyleDiff(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	if r.Method != http.MethodPost {
		apiErr(w, http.StatusMethodNotAllowed, "POST only")
		return
	}
	var body struct {
		From string `json:"from"`
		To   string `json:"to"`
	}
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		apiErr(w, http.StatusBadRequest, "body must be JSON {from, to}")
		return
	}
	fromQ, err1 := url.ParseQuery(body.From)
	toQ, err2 := url.ParseQuery(body.To)
	if err1 != nil || err2 != nil {
		apiErr(w, http.StatusBadRequest, "from/to must be url-encoded mariner queries")
		return
	}
	// The in-place diff is single-source only. A multi-pack ?set CSV won't resolve to
	// one set, so it 404s here and the client falls back to a full style re-fetch.
	set, ok := s.resolveStyleSet(toQ.Get("set"))
	if !ok {
		apiErr(w, http.StatusNotFound, "style-diff is single-set only (multi-pack → full re-fetch)")
		return
	}
	// Shared style context comes from the "to" (new) query — set/urls/scamin/lat/bands.
	// The engine diffs the two mariners over one structural template (colours resolve
	// per-mariner from the colortables, so scheme changes ride the diff too).
	ctx := s.styleCtxForSet(r, toQ, set)
	fromM, toM := marinerFromQuery(fromQ), marinerFromQuery(toQ)
	tmpl, err := tile57.StyleTemplate(toM.Scheme, ctx.tiles, ctx.sprite, ctx.glyphs, ctx.minZoom, ctx.maxZoom, ctx.encoding)
	if err != nil {
		apiErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	ct, err := tile57.ColortablesDefault()
	if err != nil {
		apiErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	ops, err := tile57.StyleDiff(tmpl, fromM, toM, ct, ctx.bands, ctx.scamin, ctx.lat)
	if err != nil {
		apiErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeMaybeGzip(w, r, jsonCT, ops)
}

// tile57StyleCtx is the per-request, mariner-INDEPENDENT style input (URLs, zoom
// span, SCAMIN manifest, latitude, band filter, tile encoding). Shared by
// /api/style.json and /api/style-diff so the two styles a diff compares differ
// ONLY in the mariner.
type tile57StyleCtx struct {
	tiles, sprite, glyphs string
	minZoom, maxZoom      uint32
	scamin                []int32
	lat                   float64
	bands                 []int32
	// The set's tile encoding (FormatMLT for an MLT-default bake) — the engine
	// emits `"encoding":"mlt"` on the chart source so maplibre-gl decodes MLT.
	encoding tile57.TileFormat
}

// resolveStyleSet maps a requested ?set to a real registered set for the engine
// style: the requested set if it's registered, else the sole registered set (the
// common single-pack case). With the Go engine gone, EVERY pack renders from the
// engine style — so this no longer refuses a baked pack just because it isn't the
// live "tile57" set. ok=false only when there's nothing to render or an ambiguous
// multi-pack install with no matching set (Phase 5: multi-source composition).
func (s *Server) resolveStyleSet(requested string) (string, bool) {
	if requested != "" {
		if _, ok := s.lookupSet(requested); ok {
			return requested, true
		}
	}
	if names := s.sets.names(); len(names) == 1 {
		return names[0], true
	}
	return requested, false
}

// resolveStyleSets resolves the ?set CSV to registered packs for the engine style,
// ordered coarse→fine by top zoom (so a finer pack's layers draw over a coarser one).
// An empty or all-unregistered request falls back to EVERY registered pack. Returns
// nil only when nothing is registered.
func (s *Server) resolveStyleSets(requested string) []string {
	var want []string
	if requested != "" {
		for _, name := range strings.Split(requested, ",") {
			if name = strings.TrimSpace(name); name == "" {
				continue
			}
			if _, ok := s.lookupSet(name); ok {
				want = append(want, name)
			}
		}
	}
	if len(want) == 0 {
		want = append(want, s.sets.names()...) // no valid explicit set → all registered
	}
	sort.SliceStable(want, func(i, j int) bool { return s.setMaxZoom(want[i]) < s.setMaxZoom(want[j]) })
	return want
}

// setMaxZoom is a registered set's top zoom (0 if unknown), for coarse→fine ordering.
func (s *Server) setMaxZoom(name string) uint8 {
	if src, ok := s.lookupSet(name); ok {
		return src.Meta().MaxZoom
	}
	return 0
}

// styleCtxForSet builds the shared style context for a SPECIFIC registered set: the
// tile/sprite/glyph URLs, the band filter, and (from that set) the top zoom, SCAMIN
// manifest, and centre latitude. ?scamin/?lat/?tiles override (single-set only).
func (s *Server) styleCtxForSet(r *http.Request, q url.Values, set string) tile57StyleCtx {
	base := requestOrigin(r)
	ctx := tile57StyleCtx{
		// Stamp the bake-generation token onto the default tile URL so engine-mode
		// tiles are content-addressed and cacheable exactly like the TileJSON path
		// (serveTile keys immutable caching on ?g). A ?tiles override is used verbatim.
		tiles:  orDefault(q.Get("tiles"), fmt.Sprintf("%s/tiles/%s/{z}/{x}/{y}.mvt%s", base, set, genQuery(s.packGen(set)))),
		sprite: orDefault(q.Get("sprite"), base+"/sprite"),
		glyphs: orDefault(q.Get("glyphs"), base+"/glyphs/{fontstack}/{range}.pbf"),
		bands:  parseBands(q.Get("bands")),
	}
	// The style is band-independent — the merged zoom-gate by default (one self-gating
	// zoom-expression layer per render-type), or the exact live filter-gate under
	// ?scaminexact. The engine no longer turns a SCAMIN manifest into per-value #sm
	// bucket layers, so ctx.scamin stays empty here. The manifest still rides the
	// TileJSON (served by the tile route) as the filter-gate client's ladder crossings.
	if src, ok := s.lookupSet(set); ok {
		meta := src.Meta()
		ctx.minZoom = uint32(meta.MinZoom) // the set's real tile floor — MapLibre requests nothing below the source minzoom
		ctx.maxZoom = uint32(meta.MaxZoom) // live ENC = z18 (berthing); don't clamp to the engine's z16 default
		ctx.encoding = tile57.EncodingFormat(meta.TileType)
		ctx.lat = (meta.S + meta.N) / 2 // bounds-centre latitude for the scale→zoom map
	}
	if v := q.Get("lat"); v != "" {
		if f, err := strconv.ParseFloat(v, 64); err == nil {
			ctx.lat = f
		}
	}
	return ctx
}

// build generates the full MapLibre style for one mariner over the shared context. The
// chart source's zoom span is pinned to the set's real one: minzoom is emitted verbatim
// (an inflated floor blanks every zoom below it — MapLibre never under-zooms a vector
// source), and maxzoom 0 would clamp to the engine's z16 default and drop the finest
// band's z17–18 (MapLibre overzooms for free).
func (c tile57StyleCtx) build(m tile57.Mariner) ([]byte, error) {
	return tile57.Style(m.Scheme, c.tiles, c.sprite, c.glyphs, c.minZoom, c.maxZoom, c.encoding, m, c.bands, c.scamin, c.lat)
}

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

// requestOrigin reconstructs the scheme://host the client reached us on, for the
// absolute URLs MapLibre needs in the style document.
func requestOrigin(r *http.Request) string {
	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	return scheme + "://" + r.Host
}

// parseBands parses a CSV of band ranks ("0,1,2") into a slice; nil for "" (all).
func parseBands(csv string) []int32 {
	if csv == "" {
		return nil
	}
	var out []int32
	for _, p := range strings.Split(csv, ",") {
		if n, err := strconv.Atoi(strings.TrimSpace(p)); err == nil {
			out = append(out, int32(n))
		}
	}
	return out
}

// marinerFromQuery builds the S-52 mariner selection from the request query, starting
// from the engine defaults so any omitted param keeps its default — the client sends
// its DEFAULT_MARINER state as query params (same key names) so the engine bakes the
// live display into the style. Bools accept "1"/"true"; floats parse leniently.
func marinerFromQuery(q url.Values) tile57.Mariner {
	m := tile57.MarinerDefaults()
	m.Scheme = tile57.SchemeFromString(q.Get("scheme"))
	boolP := func(key string, dst *bool) {
		if v := q.Get(key); v != "" {
			*dst = v == "1" || v == "true"
		}
	}
	floatP := func(key string, dst *float64) {
		if f, err := strconv.ParseFloat(q.Get(key), 64); err == nil {
			*dst = f
		}
	}
	floatP("shallowContour", &m.ShallowContour)
	floatP("safetyContour", &m.SafetyContour)
	floatP("deepContour", &m.DeepContour)
	floatP("safetyDepth", &m.SafetyDepth)
	boolP("fourShadeWater", &m.FourShadeWater)
	switch q.Get("depthUnit") {
	case "ft":
		m.DepthUnit = tile57.DepthFeet
	case "m":
		m.DepthUnit = tile57.DepthMeters
	}
	boolP("displayBase", &m.DisplayBase)
	boolP("displayStandard", &m.DisplayStandard)
	boolP("displayOther", &m.DisplayOther)
	boolP("dataQuality", &m.DataQuality)
	boolP("showInformCallouts", &m.ShowInformCallouts)
	boolP("showMetaBounds", &m.ShowMetaBounds)
	boolP("showIsolatedDangersShallow", &m.ShowIsolatedDangersShallow)
	// S-52 §10.1.10 overscale indication (AP(OVERSC01)) — engine default true.
	boolP("showOverscale", &m.ShowOverscale)
	switch q.Get("boundaryStyle") {
	case "plain":
		m.BoundaryStyle = tile57.BoundaryPlain
	case "symbolized":
		m.BoundaryStyle = tile57.BoundarySymbolized
	}
	boolP("simplifiedPoints", &m.SimplifiedPoints)
	boolP("showFullSectorLines", &m.ShowFullSectorLines)
	boolP("textNames", &m.TextNames)
	boolP("showLightDescriptions", &m.ShowLightDescriptions)
	boolP("textOther", &m.TextOther)
	boolP("dateDependent", &m.DateDependent)
	boolP("highlightDateDependent", &m.HighlightDateDependent)
	if v := q.Get("dateView"); v != "" {
		m.DateView = v
	}
	boolP("ignoreScamin", &m.IgnoreScamin)
	// The merged zoom-gate is the DEFAULT (ScaminFilterGate off → the engine's
	// self-gating zoom-expression, one layer per render-type). ?scaminexact opts INTO
	// the exact live filter-gate (the client rewrites curDenom via setFilter on ladder
	// crossings — scamin-layers.md). The legacy ?scaminMerge param is now a no-op: its
	// behavior (empty manifest, filter-gate off) is exactly the default.
	boolP("scaminFilterGate", &m.ScaminFilterGate)
	floatP("sizeScale", &m.SizeScale)
	m.ViewingGroupsOff = parseBands(q.Get("viewingGroupsOff")) // CSV of vg ids turned off
	return m
}
